PRESET_FIELD_BLOCKLIST = {
    "rna_type",
    "name",
    "editing",
    "is_gear",
    "gear_type",
    "preset",
    "preview_bore",
    "rigging_enabled",
    "driver",
    "root_driver",
    "offset_initial",
    "driver_offset",
    "parallel_offset",
    "pitch_offset",
    "rigging_mode",
    "chain_actuation",
    "intersect_samples",
    "reverse_parallel_solve",
    "rig_tree",
    "rig_host",
    "rigging_node",
    "intersect_solve_recursive",
    "intersect_solve_from_root",
    "refresh_rig",
}

PRESET_PROP_GROUPS = {
    "base": {
        "herringbone",
        "module",
        "helix_angle",
        "z_resolution",
        "pressure_angle",
        "pitch_angle",
        "length",
        "diameter",
        "width",
        "backlash",
        "height",
        "rotate",
        "teeth",
        "undercut",
        "shift",
        "complexity",
        "head",
        "clearance",
        "reverse_pitch",
    },
    "tooth_mod": {
        "tooth_mod_enabled",
        "tooth_taper",
        "tooth_taper_offset",
        "tip_relief",
        "tip_relief_resolution",
        "root_relief",
        "root_relief_resolution",
        "worm_cut",
        "worm_cut_scale",
        "flank_modifications_enum",
        "flank_modification",
        "flank_mod_param_a",
        "flank_mod_param_b",
    },
    "bore": {
        "bore_enabled",
        "bore",
        "bore_size",
        "bore_param_a",
        "bore_param_b",
        "bore_resolution",
        "bore_subtype",
    },
    "extrusion": {
        "extrusion_enabled",
        "extrusion_size",
        "extrusion_radius",
        "extrusion_top",
        "extrusion_bottom",
        "extrusion_resolution",
    },
    "set_screw": {
        "set_screw_enabled",
        "set_screw",
        "set_screw_offset",
        "set_screw_radius",
        "set_screw_resolution",
        "set_screw_angle",
    },
    "general": {
        "scaler",
        "bool_solver",
        "do_crease",
        "crease",
        "add_weld",
        "weld_dist",
    },
}
